In [1]:
import pandas as pd
import numpy as np

###  1.	Create a 2D array and print the dim and shape

In [2]:
d2= np.array([[1,2,3,4], [5,6,7,8]])
d2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
# To find di,emsion of an array
np.ndim(d2)

2

In [4]:
## To find the Shape of an array
np.shape(d2)

(2, 4)

### 2.	Create an array of 20 numbers using arange function and slice the values between 10 to 15

In [5]:
## To create an array of 20 numbers

a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
## to Slice the value between 10 to 15

a[10:16]

array([10, 11, 12, 13, 14, 15])

### 3.	Create 2 arrays of 7X5 dimension and broadcast between the 2 arrays using 
a.	Addition
b.	Subtraction
c.	Multiplication
d.	Division


In [7]:
## Creating two array of 7X5

a1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],
              [21,22,23,24,25],[26,27,28,29,30],[31,32,33,34,35]])
a2 = np.array([[36, 37, 38, 39, 40],[ 41, 42, 43, 44, 45],[ 46, 47, 48, 49, 50],
               [51, 52,53, 54, 55],[56, 57,58, 59, 60], [61, 62, 63, 64, 65], 
               [66, 67, 68, 69,70]])

## Broadcasting

In [8]:
## Addition of Two arrays 'a1' and 'a2'

np.add(a1,a2)

array([[ 37,  39,  41,  43,  45],
       [ 47,  49,  51,  53,  55],
       [ 57,  59,  61,  63,  65],
       [ 67,  69,  71,  73,  75],
       [ 77,  79,  81,  83,  85],
       [ 87,  89,  91,  93,  95],
       [ 97,  99, 101, 103, 105]])

In [9]:
## Subtraction of Two arrays 'a1' and 'a2'

np.subtract(a1,a2)

array([[-35, -35, -35, -35, -35],
       [-35, -35, -35, -35, -35],
       [-35, -35, -35, -35, -35],
       [-35, -35, -35, -35, -35],
       [-35, -35, -35, -35, -35],
       [-35, -35, -35, -35, -35],
       [-35, -35, -35, -35, -35]])

In [10]:
## Multiplication of Two arrays 'a1' and 'a2'

np.multiply(a1,a2)

array([[  36,   74,  114,  156,  200],
       [ 246,  294,  344,  396,  450],
       [ 506,  564,  624,  686,  750],
       [ 816,  884,  954, 1026, 1100],
       [1176, 1254, 1334, 1416, 1500],
       [1586, 1674, 1764, 1856, 1950],
       [2046, 2144, 2244, 2346, 2450]])

In [11]:
## Division of Two arrays 'a1' and 'a2'

np.divide(a1,a2)

array([[0.02777778, 0.05405405, 0.07894737, 0.1025641 , 0.125     ],
       [0.14634146, 0.16666667, 0.18604651, 0.20454545, 0.22222222],
       [0.23913043, 0.25531915, 0.27083333, 0.28571429, 0.3       ],
       [0.31372549, 0.32692308, 0.33962264, 0.35185185, 0.36363636],
       [0.375     , 0.38596491, 0.39655172, 0.40677966, 0.41666667],
       [0.42622951, 0.43548387, 0.44444444, 0.453125  , 0.46153846],
       [0.46969697, 0.47761194, 0.48529412, 0.49275362, 0.5       ]])

### 4.	Create 2 incompatible arrays for broadcast and print out the error

In [15]:
a1 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
a2 = np.array([[2,4,6,8],[10,12,14,16]])
a1,a2

(array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]),
 array([[ 2,  4,  6,  8],
        [10, 12, 14, 16]]))

In [16]:
b1= a1+a2

ValueError: operands could not be broadcast together with shapes (2,6) (2,4) 

### 5.	Create two arrays of any dimension and perform vstack and hstack

In [59]:
a1 = np.array([1,2,3,4,7,8,9,10])
a2 = np.array([[2,4,6,8],[10,12,14,16]])

In [60]:
a1

array([ 1,  2,  3,  4,  7,  8,  9, 10])

In [65]:
np.vstack(a1) ## Stack Vertically

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [62]:
np.hstack(a2) # Stack Horizontaly

array([ 2,  4,  6,  8, 10, 12, 14, 16])

### 6.	Append two arrays using axis = 0 and axis = 1

In [66]:
a1 = np.array([[1,2,3,4],[7,8,9,10]])
a2 = np.array([[2,4,6,8],[10,12,14,16]])

In [69]:
np.append(a1,a2, axis =0) ## append two arrays Vertically

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10],
       [ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [70]:
np.append(a1,a2, axis =1) ## append two arrays Horizontally

array([[ 1,  2,  3,  4,  2,  4,  6,  8],
       [ 7,  8,  9, 10, 10, 12, 14, 16]])

### 7.	Create a dataframe for 8 X 4 dimension using list of lists and name the columns while dataframe creation

In [113]:
pd.DataFrame([['sUB',85,74], ['aNA',34,55]], columns=['Sub','sen','Ram'])

Sub  sen  Ram
0  sUB   85   74
1  aNA   34   55

In [92]:
pd.DataFrame?

In [128]:
d1 = pd.DataFrame([['Sub1',85,74,96],['Sub2',83,87,67],['Sub3',95,81,86],
              ['Sub4',85,75,76],['Sub5',96,63,95],['Sub6',75,76,86],
              ['Sub7',95,83,99],['Sub8',91,78,89]],
            columns=['Subject','Rahul','Ram','Raju'])

In [141]:
d1 ## created 8X4 dimension dataframe using list of list

Subject  Rahul  Ram  Raju
0    Sub1     85   74    96
1    Sub2     83   87    67
2    Sub3     95   81    86
3    Sub4     85   75    76
4    Sub5     96   63    95
5    Sub6     75   76    86
6    Sub7     95   83    99
7    Sub8     91   78    89

In [142]:
d1.shape

(8, 4)

### 8.	Create a dataframe of 4 X 8 dimension using a dictionary

In [191]:
d2 = pd.DataFrame({'Name':['Raju','Rahul','Sugumar','Suresh'], 
             'Sub1':[85,74,96,83],'Sub2':[87,67,95,81],
             'Sub3':[87,65,86,86],      
             'Sub4':[85,75,76,96],'Sub5':[96,63,95,88],
             'Sub6':[75,76,86,77],'Sub7':[95,83,99,76]})

In [192]:
d2 ## created 4X8 dataframe using dictionary

Name  Sub1  Sub2  Sub3  Sub4  Sub5  Sub6  Sub7
0     Raju    85    87    87    85    96    75    95
1    Rahul    74    67    65    75    63    76    83
2  Sugumar    96    95    86    76    95    86    99
3   Suresh    83    81    86    96    88    77    76

In [193]:
d2.shape

(4, 8)

### 9.	Use loc and iloc to subset the data for the above dataframe

## LOC

In [257]:
d2

Name  Sub1  Sub2  Sub3  Sub4  Sub5  Sub6  Sub7
0     Raju    85    87    87    85    96    75    95
1    Rahul    74    67    65    75    63    76    83
2  Sugumar    96    95    86    76    95    86    99
3   Suresh    83    81    86    96    88    77    76

In [263]:
d2.loc[:1]

Name  Sub1  Sub2  Sub3  Sub4  Sub5  Sub6  Sub7
0   Raju    85    87    87    85    96    75    95
1  Rahul    74    67    65    75    63    76    83

In [269]:
d2.loc[2:3,['Sub1','Sub2']]

Sub1  Sub2
2    96    95
3    83    81

### ILOC

In [267]:
d2.iloc[2:3,0:6] 

Name  Sub1  Sub2  Sub3  Sub4  Sub5
2  Sugumar    96    95    86    76    95

In [219]:
d5 =d2.iloc[[1,2,3],[1,2,3,4,5,6,7]]

In [220]:
d5

Sub1  Sub2  Sub3  Sub4  Sub5  Sub6  Sub7
1    74    67    65    75    63    76    83
2    96    95    86    76    95    86    99
3    83    81    86    96    88    77    76

In [230]:
d5.iloc[lambda x : x.index % 2 ==0]

Sub1  Sub2  Sub3  Sub4  Sub5  Sub6  Sub7
2    96    95    86    76    95    86    99

### 10.	How to check the total number of not null values in a column?

In [237]:
d11 = pd.DataFrame({'Name':['Raju','Rahul','Sugumar','Suresh'], 
             'Sub1':[85,np.nan,96,83],'Sub2':[87,67,95,81],
             'Sub3':[87,65,86,np.nan],      
             'Sub4':[85,np.nan,76,96],'Sub5':[96,63,95,88],
             'Sub6':[np.nan,76,86,77],'Sub7':[95,83,99,76]})

In [238]:
d11 ## data frame with null values

Name  Sub1  Sub2  Sub3  Sub4  Sub5  Sub6  Sub7
0     Raju  85.0    87  87.0  85.0    96   NaN    95
1    Rahul   NaN    67  65.0   NaN    63  76.0    83
2  Sugumar  96.0    95  86.0  76.0    95  86.0    99
3   Suresh  83.0    81   NaN  96.0    88  77.0    76

In [252]:
d11.notnull().sum() ## Tota lnumber of not null values in each column

Name    4
Sub1    3
Sub2    4
Sub3    3
Sub4    3
Sub5    4
Sub6    3
Sub7    4
dtype: int64

###  11.	Create a dataframe with missing values and fill them all with 100

In [ ]:
d11 = pd.DataFrame({'Name':['Raju','Rahul','Sugumar','Suresh'], 
             'Sub1':[85,np.nan,96,83],'Sub2':[87,67,95,81],
             'Sub3':[87,65,86,np.nan],      
             'Sub4':[85,np.nan,76,96],'Sub5':[96,63,95,88],
             'Sub6':[np.nan,76,86,77],'Sub7':[95,83,99,76]})

In [253]:
d11

Name  Sub1  Sub2  Sub3  Sub4  Sub5  Sub6  Sub7
0     Raju  85.0    87  87.0  85.0    96   NaN    95
1    Rahul   NaN    67  65.0   NaN    63  76.0    83
2  Sugumar  96.0    95  86.0  76.0    95  86.0    99
3   Suresh  83.0    81   NaN  96.0    88  77.0    76

In [270]:
d11.fillna(100)

Name   Sub1  Sub2   Sub3   Sub4  Sub5   Sub6  Sub7
0     Raju   85.0    87   87.0   85.0    96  100.0    95
1    Rahul  100.0    67   65.0  100.0    63   76.0    83
2  Sugumar   96.0    95   86.0   76.0    95   86.0    99
3   Suresh   83.0    81  100.0   96.0    88   77.0    76

### 12.	Create a dataframe with missing values and drop the null records

In [272]:
d11.dropna()

Name  Sub1  Sub2  Sub3  Sub4  Sub5  Sub6  Sub7
2  Sugumar  96.0    95  86.0  76.0    95  86.0    99

### 13.	Perform following aggregation task on below table 

In [334]:
pd1 = pd.DataFrame({'Age': [25,30,45,35,33,35,25,52,21,24,48,22,27,28,21,51,23],
              'Hair Color':['Black','Black','Red','Blond','Brown','Brown',
                             'Black','Brown','Red','Blond','Black','Black',
                             'Brown','Black','Blond','Black','Brown'],
             'U.S.Region': ['Southwest','Northwest','Northeast','Southwest',
                            'Southwest','Northeast','Southwest','Southeast',
                            'Southwest','Northeast','Southwest','Southwest',
                            'Northeast','Southeast','Southeast','Northwest',
                            'Southeast'],
             'Validation': [1,1,1,0,0,0,0,0,1,0,1,0,0,1,1,0,1]})

In [335]:
pd1

Age Hair Color U.S.Region  Validation
0    25      Black  Southwest           1
1    30      Black  Northwest           1
2    45        Red  Northeast           1
3    35      Blond  Southwest           0
4    33      Brown  Southwest           0
5    35      Brown  Northeast           0
6    25      Black  Southwest           0
7    52      Brown  Southeast           0
8    21        Red  Southwest           1
9    24      Blond  Northeast           0
10   48      Black  Southwest           1
11   22      Black  Southwest           0
12   27      Brown  Northeast           0
13   28      Black  Southeast           1
14   21      Blond  Southeast           1
15   51      Black  Northwest           0
16   23      Brown  Southeast           1

### a.	Get the average age group by Region

In [352]:
pd1[['U.S.Region','Age']].groupby('U.S.Region').mean()

Age
U.S.Region           
Northeast   32.750000
Northwest   40.500000
Southeast   31.000000
Southwest   29.857143

### b.	Get the sum of Age and Validation group by Hair color and then reset the index

In [345]:
pd1.groupby("Hair Color").sum().reset_index()

Hair Color  Age  Validation
0      Black  229           4
1      Blond   80           1
2      Brown  170           1
3        Red   66           2

### c.	Get the mean and median of Age group by Region

In [349]:
pd1[['U.S.Region','Age']].groupby('U.S.Region').mean()

Age
U.S.Region           
Northeast   32.750000
Northwest   40.500000
Southeast   31.000000
Southwest   29.857143

In [350]:
pd1[['U.S.Region','Age']].groupby('U.S.Region').median()

Age
U.S.Region      
Northeast   31.0
Northwest   40.5
Southeast   25.5
Southwest   25.0

### 14.	Split the below table into half and perform merge (inner, left and right) on Region. One example for each type of merge (inner, left and right)

In [357]:
t1 = pd1.loc[:8]
t2 = pd1.loc[9:]

In [361]:
t1

Age Hair Color U.S.Region  Validation
0   25      Black  Southwest           1
1   30      Black  Northwest           1
2   45        Red  Northeast           1
3   35      Blond  Southwest           0
4   33      Brown  Southwest           0
5   35      Brown  Northeast           0
6   25      Black  Southwest           0
7   52      Brown  Southeast           0
8   21        Red  Southwest           1

In [362]:
t2

Age Hair Color U.S.Region  Validation
9    24      Blond  Northeast           0
10   48      Black  Southwest           1
11   22      Black  Southwest           0
12   27      Brown  Northeast           0
13   28      Black  Southeast           1
14   21      Blond  Southeast           1
15   51      Black  Northwest           0
16   23      Brown  Southeast           1

In [365]:
t1.merge(t2, how ='inner', on ='U.S.Region')

Age_x Hair Color_x U.S.Region  Validation_x  Age_y Hair Color_y  \
0      25        Black  Southwest             1     48        Black   
1      25        Black  Southwest             1     22        Black   
2      35        Blond  Southwest             0     48        Black   
3      35        Blond  Southwest             0     22        Black   
4      33        Brown  Southwest             0     48        Black   
5      33        Brown  Southwest             0     22        Black   
6      25        Black  Southwest             0     48        Black   
7      25        Black  Southwest             0     22        Black   
8      21          Red  Southwest             1     48        Black   
9      21          Red  Southwest             1     22        Black   
10     30        Black  Northwest             1     51        Black   
11     45          Red  Northeast             1     24        Blond   
12     45          Red  Northeast             1     27        Brown   
13     35        Brown  Northeast             0     24        Blond   
14     35        Brown  Northeast             0     27        Brown   
15     52        Brown  Southeast             0     28        Black   
16     52        Brown  Southeast             0     21        Blond   
17     52        Brown  Southeast             0     23        Brown   

    Validation_y  
0              1  
1              0  
2              1  
3              0  
4              1  
5              0  
6              1  
7              0  
8              1  
9              0  
10             0  
11             0  
12             0  
13             0  
14             0  
15             1  
16             1  
17             1

In [366]:
t1.merge(t2, how ='left', on ='U.S.Region')

Age_x Hair Color_x U.S.Region  Validation_x  Age_y Hair Color_y  \
0      25        Black  Southwest             1     48        Black   
1      25        Black  Southwest             1     22        Black   
2      30        Black  Northwest             1     51        Black   
3      45          Red  Northeast             1     24        Blond   
4      45          Red  Northeast             1     27        Brown   
5      35        Blond  Southwest             0     48        Black   
6      35        Blond  Southwest             0     22        Black   
7      33        Brown  Southwest             0     48        Black   
8      33        Brown  Southwest             0     22        Black   
9      35        Brown  Northeast             0     24        Blond   
10     35        Brown  Northeast             0     27        Brown   
11     25        Black  Southwest             0     48        Black   
12     25        Black  Southwest             0     22        Black   
13     52        Brown  Southeast             0     28        Black   
14     52        Brown  Southeast             0     21        Blond   
15     52        Brown  Southeast             0     23        Brown   
16     21          Red  Southwest             1     48        Black   
17     21          Red  Southwest             1     22        Black   

    Validation_y  
0              1  
1              0  
2              0  
3              0  
4              0  
5              1  
6              0  
7              1  
8              0  
9              0  
10             0  
11             1  
12             0  
13             1  
14             1  
15             1  
16             1  
17             0

In [367]:
t1.merge(t2, how ='right', on ='U.S.Region')

Age_x Hair Color_x U.S.Region  Validation_x  Age_y Hair Color_y  \
0      45          Red  Northeast             1     24        Blond   
1      35        Brown  Northeast             0     24        Blond   
2      25        Black  Southwest             1     48        Black   
3      35        Blond  Southwest             0     48        Black   
4      33        Brown  Southwest             0     48        Black   
5      25        Black  Southwest             0     48        Black   
6      21          Red  Southwest             1     48        Black   
7      25        Black  Southwest             1     22        Black   
8      35        Blond  Southwest             0     22        Black   
9      33        Brown  Southwest             0     22        Black   
10     25        Black  Southwest             0     22        Black   
11     21          Red  Southwest             1     22        Black   
12     45          Red  Northeast             1     27        Brown   
13     35        Brown  Northeast             0     27        Brown   
14     52        Brown  Southeast             0     28        Black   
15     52        Brown  Southeast             0     21        Blond   
16     30        Black  Northwest             1     51        Black   
17     52        Brown  Southeast             0     23        Brown   

    Validation_y  
0              0  
1              0  
2              1  
3              1  
4              1  
5              1  
6              1  
7              0  
8              0  
9              0  
10             0  
11             0  
12             0  
13             0  
14             1  
15             1  
16             0  
17             1

### 15.	Split the below table and perform concat row wise and column wise

In [386]:
pd.concat([t1,t2], axis = 1) ## Column Wise

Age Hair Color U.S.Region  Validation   Age Hair Color U.S.Region  \
0   25.0      Black  Southwest         1.0   NaN        NaN        NaN   
1   30.0      Black  Northwest         1.0   NaN        NaN        NaN   
2   45.0        Red  Northeast         1.0   NaN        NaN        NaN   
3   35.0      Blond  Southwest         0.0   NaN        NaN        NaN   
4   33.0      Brown  Southwest         0.0   NaN        NaN        NaN   
5   35.0      Brown  Northeast         0.0   NaN        NaN        NaN   
6   25.0      Black  Southwest         0.0   NaN        NaN        NaN   
7   52.0      Brown  Southeast         0.0   NaN        NaN        NaN   
8   21.0        Red  Southwest         1.0   NaN        NaN        NaN   
9    NaN        NaN        NaN         NaN  24.0      Blond  Northeast   
10   NaN        NaN        NaN         NaN  48.0      Black  Southwest   
11   NaN        NaN        NaN         NaN  22.0      Black  Southwest   
12   NaN        NaN        NaN         NaN  27.0      Brown  Northeast   
13   NaN        NaN        NaN         NaN  28.0      Black  Southeast   
14   NaN        NaN        NaN         NaN  21.0      Blond  Southeast   
15   NaN        NaN        NaN         NaN  51.0      Black  Northwest   
16   NaN        NaN        NaN         NaN  23.0      Brown  Southeast   

    Validation  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  
5          NaN  
6          NaN  
7          NaN  
8          NaN  
9          0.0  
10         1.0  
11         0.0  
12         0.0  
13         1.0  
14         1.0  
15         0.0  
16         1.0

In [389]:
pd.concat([t1,t2], axis = 0) ## Row Wise

Age Hair Color U.S.Region  Validation
0    25      Black  Southwest           1
1    30      Black  Northwest           1
2    45        Red  Northeast           1
3    35      Blond  Southwest           0
4    33      Brown  Southwest           0
5    35      Brown  Northeast           0
6    25      Black  Southwest           0
7    52      Brown  Southeast           0
8    21        Red  Southwest           1
9    24      Blond  Northeast           0
10   48      Black  Southwest           1
11   22      Black  Southwest           0
12   27      Brown  Northeast           0
13   28      Black  Southeast           1
14   21      Blond  Southeast           1
15   51      Black  Northwest           0
16   23      Brown  Southeast           1